# Generated by Django 3.2.6 on 2021-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='User')),
                ('titulo', models.CharField(max_length=25, verbose_name='Titulo')),
                ('texto', models.TextField(max_length=280, verbose_name='Texto')),
                ('dataPub', models.DateField(auto_now=True)),
            ],
        ),
    ]
